version: '3.1'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: twitter
    ports:
      - "27017:27017"
    volumes:
      - ./config/database:/docker-entrypoint-initdb.d