server:
  port: 8091

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: twitter

eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka