spring:
  application:
    name: twitter-clone-api
  data:
    mongodb:
      uri: "mongodb+srv://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_URL}?retryWrites=true&w=majority"
      password: "${DATABASE_PASSWORD}"
      username: "${DATABASE_USERNAME}"
      database: twitter
  webFlux:
    jwt:
      password:
        encoder:
          secret: "${JWT_SECRET}"
          iteration: 8
          keyLength: 256
      secret: "${JWT_ENCODER_SECRET}"
      expiration: 28800