spring:
  application:
    name: twitter-clone-api
  data:
    mongodb:
      uri: "mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}"
      host: localhost
      password: root
      username: root
      port: 27017
      database: twitter
  webFlux:
    jwt:
      password:
        encoder:
          secret: testSecret
          iteration: 8
          keyLength: 256
      secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
      expiration: 28800